name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@b857927a9d6d76c23c816e2910af962ceb8e2b9d
        with:
          repo-token: ${{ secrets.CI_GITHUB_TOKEN }}
          allowed-actors: renovate[bot]
